apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps-21
    port: 21
    targetPort: 21
  - name: ftps-data1
    port: 21101
    targetPort: 21101
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_i
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - if [[ $(ps | grep vsftpd | head -n -1 | wc -l) = 0 ]]; then exit 0; else exit 1; fi
          initialDelaySeconds: 60
          periodSeconds: 10
        # livenessProbe: 
        #   failureThreshold: 1
        #   httpGet: 
        #     path: /weblearner/health
        #     port: 8085
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
 # Liveness probe failed: OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
