apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps
    protocol: TCP
    port: 21
    targetPort: 21
  - name: ftps-data
    protocol: TCP
    port: 20
    targetPort: 20
  - name: ftps-psv1
    protocol: TCP
    port: 21101
    targetPort: 21101
  - name: ftps-psv2
    protocol: TCP
    port: 21100
    targetPort: 21100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_i
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep vsftpd && pgrep telegraf'
          initialDelaySeconds: 30
          periodSeconds: 10
        # livenessProbe: 
        #   failureThreshold: 1
        #   httpGet: 
        #     path: /weblearner/health
        #     port: 8085
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # if [[ $(ps | grep vsftpd | head -n -1 | wc -l) = 0 ]]; then exit 0; else exit 1; fi
        ports:
        - containerPort: 20
          hostPort: 20
        - containerPort: 21
          hostPort: 21
        - containerPort: 21101
          hostPort: 21101
        - containerPort: 21100
          hostPort: 21100
        