apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
    - name: phpmyadmin
      protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin_i
          imagePullPolicy: Never
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/bash
        #     - -c
        #     - /livenessProbe.sh
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
          ports:
          - containerPort: 5000
            name: phpmyadmin
