apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: wordpress-service
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
    - name: wordpress
      protocol: TCP
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_i
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep nginx && pgrep php-fpm && pgrep telegraf'
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 5050
          name: wordpress
